### PR TITLE
libwebp support for linux

### PR DESCRIPTION
**Pull request by weltling**

### CODE REVIEW

**Comment by weltling** [comment]
@cmb69 please check this, if it's ok, probably we're complete.

Thanks.

**Comment by weltling** [comment]
Also, as we in beta now, we should handle the option breakage somehow :( 

Thanks.

**Comment by cmb69** [comment]
@weltling Thanks. I gave it try and building on Linux works fine. However, now I've noticed that there is not a single test for imagecreatefromwebp() or imagewebp(). The latter is supposed to be tested by imagewebp_nullbyte_injection.phpt (at least the function is called), but the test was always skipped due to [gd_info() not reporting WebP support](https://bugs.php.net/bug.php?id=70047). Even though this bug has been fixed in the meantime the test still is skipped due to checking for "WEBP Support" instead of "WebP Support". Fixing this makes the test pass, but IMO we need tests for the actual functionality of the image*webp() functions, so I'll catch up on that first.

> Also, as we in beta now, we should handle the option breakage somehow :(

Can't we consider the current behavior (i..e still relying on libvpx for PHP 7.0.0beta1) as bug?

**Comment by weltling** [comment]
Maybe you could decide to merge this into your fork. Thanks for the check and the work you've done :)

Yeah, more tests cannot be too much.

I would decide libvpx usage as an issue because a) its functionality is an overkill where there's a specialized libwebp and b) there's an issue with maintaining libvpx upgrades an Windows as dependency.

/cc @pierrejoye @remicollet @KalleZ

Thanks.

**Comment by cmb69** [comment]
@weltling I have merged the PR (thanks!), and rebased onto current master. The few new WebP related tests run fine on Win7 and Debian Jessie (both 64bit).

Shall I make a PR?

**Comment by pierrejoye** [comment]
Hello :)

Yes, webp should replace vpx. I already replace it upstream. Thanks :))

**Comment by weltling** [comment]
@cmb69 yeah, a PR would make sense anyway.

Thanks.

**Comment by cmb69** [comment]
Okay, I've submitted PR #1429.

**Pull request merged**
